version: "3.8"

volumes:
  starten-postgres:

services:
  postgres:
    image: "postgres:alpine"
    environment:
      - "POSTGRES_DB=starten_db"
      - "POSTGRES_USER=starten"
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "5432:5432"
    volumes:
      - "starten-postgres:/var/lib/postgresql/data"
