version: "3.8"

volumes:
  startern-postgres:

services:
  postgres:
    image: "postgres:alpine"
    environment:
      - "POSTGRES_DB=startern_db"
      - "POSTGRES_USER=startern"
      - "POSTGRES_PASSWORD=secret"
    ports:
      - "5432:5432"
    volumes:
      - "startern-postgres:/var/lib/postgresql/data"
